modLoader = "javafml"
loaderVersion = "[39,)"
issueTrackerURL = "https://github.com/shedaniel/architectury/issues"
license = "GNU LGPLv3"

[[mods]]
modId = "architectury"
version = "${version}"
displayName = "Architectury"
authors = "shedaniel"
description = '''
A intermediary api aimed to ease developing multiplatform mods.
'''
logoFile = "icon.png"
license = "LGPL-3"

[[dependencies.architectury]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.architectury]]
modId = "forge"
mandatory = true
versionRange = "[39.0.8,)"
ordering = "NONE"
side = "BOTH"
